### ISSUE TITLE
Roadmap for 1.0.0

### ISSUE THREAD

**Issue by bvenn** [CSBiology/FSharp.Stats#95]
Features that are needed for 1.0.0 are tracked here. Feel free to add suggestions/issues.

- [ ] integration of interactive notebooks
- [ ] move docs to newest FSharp.Formatting for `fsdocs`
- [ ] restructure fitting module #94
- [ ] How to rework the linear algebra module is open for discussion (MKL.NET)
- [x] update installation instructions #93
- [ ] update build.fsx
- [x] drop optimization project in favour for flips
